modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory
license = "MIT"
issueTrackerURL = "https://github.com/AnonymousHacker1279/IWCompatibilityBridge/issues" #optional

[[mods]] #mandatory
modId = "iwcompatbridge" #mandatory
version = "${mod_version}" #mandatory
displayName = "Immersive Weapons Compatibility Bridge" #mandatory
displayURL = "https://www.curseforge.com/minecraft/mc-mods/immersive-weapons-compatibility-bridge" #optional
updateJSONURL = "https://raw.githubusercontent.com/AnonymousHacker1279/IWCompatibilityBridge/master/update.json"
logoFile = "logo.png" #optional
credits = "Written by AnonymousHacker1279" #optional
authors = "AnonymousHacker1279" #optional
description = '''
The Immersive Weapons Compatibility Bridge adds compatibility to several mods.
'''

[[dependencies.iwcompatbridge]] #optional
modId = "neoforge" #mandatory
mandatory = true #mandatory
versionRange = "${neoforge_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.iwcompatbridge]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.iwcompatbridge]]
modId = "immersiveweapons"
mandatory = true
versionRange = "[1.20.2-1.28.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iwcompatbridge]]
modId = "curios"
mandatory = false
versionRange = "[6.1.0+1.20.2,)"
ordering = "NONE"
side = "BOTH"