modLoader = "javafml" #mandatory
loaderVersion = "[40,)" #mandatory
license = "MIT"
issueTrackerURL = "https://github.com/AnonymousHacker1279/ImmersiveWeapons/issues" #optional

# TODO: Replace displayURL, updateJSONURL, logoFile with proper values

[[mods]] #mandatory
modId = "iwcompatbridge" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Immersive Weapons Compatability Bridge" #mandatory
displayURL = "https://www.curseforge.com/minecraft/mc-mods/immersive-weapons" #optional
updateJSONURL = "https://raw.githubusercontent.com/AnonymousHacker1279/ImmersiveWeapons/master/update.json"
logoFile = "logo.png" #optional
credits = "Written by AnonymousHacker1279" #optional
authors = "AnonymousHacker1279" #optional
description = '''
The Immersive Weapons Compatability Bridge adds compatability to several mods like JEI, WTHIT, and Patchouli.
'''

[[dependencies.iwcompatbridge]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[40.0.24,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.iwcompatbridge]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iwcompatbridge]]
modId = "immersiveweapons"
mandatory = true
versionRange = "[1.18.2-1.17.0-indev,)"
ordering = "NONE"
side = "BOTH"