modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/AnonymousHacker1279/IWCompatibilityBridge/issues"

[[mods]]
modId = "iwcompatbridge"
version = "${mod_version}"
displayName = "Immersive Weapons Compatibility Bridge"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/immersive-weapons-compatibility-bridge"
updateJSONURL = "https://raw.githubusercontent.com/AnonymousHacker1279/IWCompatibilityBridge/master/update.json"
logoFile = "logo.png"
credits = "Written by AnonymousHacker1279"
authors = "AnonymousHacker1279"
description = '''
The Immersive Weapons Compatibility Bridge adds compatibility to several mods.
'''

[[dependencies.iwcompatbridge]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.iwcompatbridge]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.iwcompatbridge]]
modId = "immersiveweapons"
type = "required"
versionRange = "[1.20.4-1.29.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iwcompatbridge]]
modId = "cobaltconfig"
type = "required"
versionRange = "[1.20.4-1.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iwcompatbridge]]
modId = "curios"
type = "optional"
versionRange = "[7.0.0-beta.3+1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iwcompatbridge]]
modId = "emi"
type = "optional"
versionRange = "[1.1.6,)"
ordering = "NONE"
side = "BOTH"